#!/bin/python3

import math
import os
import random
import re
import sys

def weirdOrNot(n):
    if n % 2 == 1:
        print('Weird')
    else:
        if 6 <= n <= 20:
            print('Weird')
        else:
            print('Not Weird')


weirdOrNot(0)
weirdOrNot(6)
weirdOrNot(3)
weirdOrNot(17)
weirdOrNot(30)